# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.component import Child, Component

__all__ = ["LightweightChart"]


class LightweightChart(Component):
    """A TradingView lightweight-charts chart as a web component, driven by its type and data."""

    tag = "lightweight-chart"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        type: Literal["line", "area", "candlestick", "bar", "histogram"] | None = None,
        data: Any = None,
        theme: Literal["light", "dark"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "type": type,
                "data": data,
                "theme": theme,
            },
            **props,
        )
