# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["LightweightChart"]


class LightweightChart(Component):
    """A TradingView lightweight-charts chart as a web component, driven by its type and data."""

    tag = "lightweight-chart"
    schema = ComponentSchema(
        tag="lightweight-chart",
        class_name="LightweightChart",
        summary="A TradingView lightweight-charts chart as a web component, driven by its type and data.",
        props=(
            PropertySchema(
                name="type", kind="enum", choices=("line", "area", "candlestick", "bar", "histogram"), default="line", description="The series type."
            ),
            PropertySchema(
                name="data",
                kind="json",
                choices=(),
                default=None,
                description="The series data: an array of points. line/area/histogram use {time, value}; candlestick/bar use {time, open, high, low, close}.",
            ),
            PropertySchema(name="theme", kind="enum", choices=("light", "dark"), default="light", description="Chart text and grid color theme."),
        ),
        events=(),
        slots=(),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        type: Literal["line", "area", "candlestick", "bar", "histogram"] | None = None,
        data: Any = None,
        theme: Literal["light", "dark"] | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "type": type,
                "data": data,
                "theme": theme,
            },
            **props,
        )
